- id: spellchecker-cli
  name: spellchecker
  entry: spellchecker
  language: node
  types: [markdown]
  description: A pre-commit implementation for spellchecker-cli
  minimum_pre_commit_version: 0.15.0
  args: ['--no-suggestions']
